AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
